### ISSUE TITLE
网站侧边栏收缩按钮点击无效

### ISSUE THREAD

**Issue by sunzehui** [zszdevelop/java-study-gitbook#39]
博主您好，看了您的文章，写的非常好
由于java代码太长，我想收缩目录面板，然而点击侧边栏收缩按钮没有反应
浏览器：Microsoft Edge 版本 115.0.1880.3 (正式版本) dev (64 位)
![image](https://github.com/zszdevelop/java-study-gitbook/assets/43507603/86033bed-9f99-4974-973a-7ef4fb54b92a)

**Comment by zszdevelop** [comment]
挂github速度太慢了、改了方案应该好点
